/*
 * Resort and restaurant data for the Disney World Match quiz.
 *
 * This is the file you edit to change recommendations. Menus, prices,
 * character lineups and dining plan rules change often, so review it
 * before each season. Last reviewed against news and Disney's site:
 * September 2026.
 *
 * Resort fields
 *   tier         value | moderate | deluxe | villa
 *   sleeps       max guests in a standard room or studio
 *   suiteSleeps  max guests in the largest suite, villa or cabin option (0 if none)
 *   transport    ways to reach parks besides buses: monorail, skyliner, boat, walk
 *   parks        ease of access, 1 (bus only) to 3 (walk, monorail or one short ride)
 *   access       reason text shown when a park the guest picked is easy to reach
 *   vibes        tropical, rustic, elegant, playful, nature, lively, quiet, modern
 *   pool         1 (basic) to 3 (standout)
 *   goodFor      young-kids, kids, teens, adults, grandparents
 *   host         for villas, the resort whose restaurants they share
 *   partner      true for hotels on Disney property that Disney doesn't run
 *   camping      true for campsites (guests bring a tent or RV)
 *   roomLabel    what the smallest unit is called, if not "Standard rooms" or "Studios"
 *
 * Restaurant fields
 *   kind         character | table | signature | quick
 *   family       true for buffets and family-style platters
 *   price        1 ($ under $15) to 4 ($$$$ over $60) per adult
 *   credits      Disney Dining Plan credits. Leave out for the usual count:
 *                table service and character meals 1, signature 2, quick service 1.
 *                Use 2 for two-credit meals, 0 if the plan isn't accepted,
 *                null if participation needs checking.
 *   creditsNote  extra detail, e.g. "1 at breakfast"
 *   chars        who appears, for character meals
 *   themes       princess, classic, pixar, starwars, animals
 *   picky / adv  0 to 2: how well it suits picky or adventurous eaters (default 1)
 *   kids / adults 0 to 2: how well it suits kids, or an adults-only group (default 1)
 *   celebrate    birthday, anniversary, first
 *   park         mk, epcot, hs, ak, springs, or resort (then set `resort` to a resort id)
 *   menu         path of the official Disney page, e.g. "magic-kingdom/crystal-palace".
 *                Without it, the menu link searches Disney's site instead.
 *   status       a short note shown on the card (refurbishments, limited time)
 */
window.PT_DATA = {
  resorts: [
    // Value
    { id: "all-star-movies", name: "All-Star Movies Resort", sub: "Value resort",
      tier: "value", sleeps: 4, suiteSleeps: 0, transport: [], parks: { mk: 1, epcot: 1, hs: 1, ak: 2 },
      vibes: ["playful"], pool: 1, goodFor: ["young-kids", "kids"],
      blurb: "Giant icons from Toy Story, 101 Dalmatians, Fantasia and The Mighty Ducks. One of the lowest room rates on property." },
    { id: "all-star-music", name: "All-Star Music Resort", sub: "Value resort",
      tier: "value", sleeps: 4, suiteSleeps: 6, suiteLabel: "Family suites", transport: [], parks: { mk: 1, epcot: 1, hs: 1, ak: 2 },
      vibes: ["playful"], pool: 1, goodFor: ["young-kids", "kids"],
      blurb: "Guitars, jukeboxes and drums the size of buildings. Family suites sleep six and are among the most affordable suites on property." },
    { id: "all-star-sports", name: "All-Star Sports Resort", sub: "Value resort",
      tier: "value", sleeps: 4, suiteSleeps: 0, transport: [], parks: { mk: 1, epcot: 1, hs: 1, ak: 2 },
      vibes: ["playful"], pool: 1, goodFor: ["kids", "teens"],
      blurb: "Football helmets, surfboards and tennis rackets as tall as the buildings. A budget-friendly pick for sports fans." },
    { id: "pop", name: "Pop Century Resort", sub: "Value resort",
      tier: "value", sleeps: 4, suiteSleeps: 0, transport: ["skyliner"], parks: { mk: 1, epcot: 2, hs: 2, ak: 1 },
      access: { epcot: "Skyliner gondola to EPCOT", hs: "Skyliner gondola to Hollywood Studios" },
      vibes: ["playful"], pool: 1, goodFor: ["kids", "teens", "adults"],
      blurb: "Decade-themed icons from the 1950s through the 1990s, with a Skyliner station for gondola rides to EPCOT and Hollywood Studios." },
    { id: "aoa", name: "Art of Animation Resort", sub: "Value resort",
      tier: "value", sleeps: 4, suiteSleeps: 6, suiteLabel: "Family suites", transport: ["skyliner"], parks: { mk: 1, epcot: 2, hs: 2, ak: 1 },
      access: { epcot: "Skyliner gondola to EPCOT", hs: "Skyliner gondola to Hollywood Studios" },
      vibes: ["playful"], pool: 2, poolNote: "The Big Blue Pool, the largest on property", goodFor: ["young-kids", "kids"],
      blurb: "Life-size scenes from Cars, Finding Nemo, The Lion King and The Little Mermaid. Family suites sleep six and have two bathrooms." },

    // Moderate
    { id: "cbr", name: "Caribbean Beach Resort", sub: "Moderate resort",
      tier: "moderate", sleeps: 5, suiteSleeps: 0, transport: ["skyliner"], parks: { mk: 1, epcot: 2, hs: 2, ak: 1 },
      access: { epcot: "Skyliner gondola to EPCOT", hs: "Skyliner gondola to Hollywood Studios" },
      vibes: ["tropical", "playful"], pool: 2, goodFor: ["kids", "teens", "grandparents"],
      blurb: "Colorful island villages around a lake, and the central hub of the Skyliner. Many rooms sleep five." },
    { id: "coronado", name: "Coronado Springs Resort", sub: "Moderate resort",
      tier: "moderate", sleeps: 4, suiteSleeps: 0, transport: [], parks: { mk: 1, epcot: 1, hs: 1, ak: 2 },
      vibes: ["lively", "elegant"], pool: 2, goodFor: ["teens", "adults"],
      blurb: "A Spanish and Mexican-inspired resort around a lake, with the Gran Destino Tower, the rooftop Toledo restaurant and a Mayan pyramid pool." },
    { id: "pofq", name: "Port Orleans – French Quarter", sub: "Moderate resort",
      tier: "moderate", sleeps: 4, suiteSleeps: 0, transport: ["boat"], parks: { mk: 1, epcot: 1, hs: 1, ak: 1 },
      vibes: ["quiet", "elegant"], pool: 2, goodFor: ["adults", "young-kids"],
      blurb: "A small, quiet New Orleans-style resort with beignets at the food court and a riverboat to Disney Springs." },
    { id: "por", name: "Port Orleans – Riverside", sub: "Moderate resort",
      tier: "moderate", sleeps: 5, suiteSleeps: 0, transport: ["boat"], parks: { mk: 1, epcot: 1, hs: 1, ak: 1 },
      vibes: ["rustic", "quiet"], pool: 2, goodFor: ["kids", "grandparents"],
      blurb: "Southern mansions and bayou buildings along the river, with a riverboat to Disney Springs. Royal Guest Rooms and Alligator Bayou rooms sleep five." },
    { id: "fw-campsites", name: "Fort Wilderness Campsites", sub: "Campground", camping: true,
      tier: "moderate", sleeps: 10, suiteSleeps: 0, transport: ["boat"], parks: { mk: 2, epcot: 1, hs: 1, ak: 1 },
      access: { mk: "Boat to Magic Kingdom" },
      vibes: ["rustic", "nature"], pool: 2, goodFor: ["kids", "grandparents"],
      blurb: "Tent and RV sites in 750 acres of pine and cypress, with a boat to Magic Kingdom, Hoop-Dee-Doo Musical Revue and campfire sing-alongs." },

    // Deluxe
    { id: "akl", name: "Animal Kingdom Lodge", sub: "Deluxe resort",
      tier: "deluxe", sleeps: 4, suiteSleeps: 0, transport: [], parks: { mk: 1, epcot: 1, hs: 1, ak: 2 },
      access: { ak: "A short bus ride to Animal Kingdom" },
      vibes: ["nature", "quiet"], pool: 2, goodFor: ["young-kids", "kids", "adults", "grandparents"],
      blurb: "Savanna-view rooms where giraffes and zebras wander past your balcony. Home of Jiko, Boma and Sanaa." },
    { id: "beach-club", name: "Beach Club Resort", sub: "Deluxe resort",
      tier: "deluxe", sleeps: 5, suiteSleeps: 0, transport: ["walk", "boat", "skyliner"], parks: { mk: 1, epcot: 3, hs: 3, ak: 1 },
      access: { epcot: "Walk to EPCOT's International Gateway", hs: "Boat or walking path to Hollywood Studios" },
      vibes: ["playful", "elegant"], pool: 3, poolNote: "Stormalong Bay, a sand-bottom pool with a shipwreck slide",
      goodFor: ["kids", "teens", "grandparents"],
      blurb: "A breezy New England beach cottage look on Crescent Lake. Walk to EPCOT and share Stormalong Bay, the best pool at Disney World." },
    { id: "yacht-club", name: "Yacht Club Resort", sub: "Deluxe resort",
      tier: "deluxe", sleeps: 5, suiteSleeps: 0, transport: ["walk", "boat", "skyliner"], parks: { mk: 1, epcot: 3, hs: 3, ak: 1 },
      access: { epcot: "Walk to EPCOT's International Gateway", hs: "Boat or walking path to Hollywood Studios" },
      vibes: ["elegant", "quiet"], pool: 3, poolNote: "Stormalong Bay, a sand-bottom pool with a shipwreck slide",
      goodFor: ["kids", "adults", "grandparents"],
      blurb: "The more polished, nautical sibling of the Beach Club. Walk to EPCOT, boat to Hollywood Studios, and share Stormalong Bay." },
    { id: "boardwalk", name: "BoardWalk Inn", sub: "Deluxe resort",
      tier: "deluxe", sleeps: 5, suiteSleeps: 0, transport: ["walk", "boat", "skyliner"], parks: { mk: 1, epcot: 3, hs: 3, ak: 1 },
      access: { epcot: "Walk to EPCOT's International Gateway", hs: "Boat or walking path to Hollywood Studios" },
      vibes: ["lively"], pool: 2, goodFor: ["teens", "adults"],
      blurb: "A 1930s Atlantic City boardwalk with street performers and evening strolls. Walk to EPCOT or Hollywood Studios." },
    { id: "contemporary", name: "Contemporary Resort", sub: "Deluxe resort",
      tier: "deluxe", sleeps: 5, suiteSleeps: 0, transport: ["monorail", "walk"], parks: { mk: 3, epcot: 2, hs: 1, ak: 1 },
      access: { mk: "Walk or take the monorail to Magic Kingdom", epcot: "Monorail to EPCOT with one transfer" },
      vibes: ["modern", "lively"], pool: 2, goodFor: ["young-kids", "kids", "teens", "adults", "grandparents"],
      blurb: "A 10-minute walk to Magic Kingdom, with the monorail running right through the building. Home of California Grill and Chef Mickey's." },
    { id: "gf", name: "Grand Floridian Resort & Spa", sub: "Deluxe resort",
      tier: "deluxe", sleeps: 5, suiteSleeps: 0, transport: ["monorail", "boat"], parks: { mk: 3, epcot: 2, hs: 1, ak: 1 },
      access: { mk: "One monorail stop to Magic Kingdom", epcot: "Monorail to EPCOT with one transfer" },
      vibes: ["elegant", "quiet"], pool: 3, poolNote: "Alice in Wonderland splash area and beach pool",
      goodFor: ["young-kids", "adults", "grandparents"],
      blurb: "Disney's flagship Victorian-style resort. One monorail stop from Magic Kingdom, with 1900 Park Fare and Victoria & Albert's." },
    { id: "poly", name: "Polynesian Village Resort", sub: "Deluxe resort",
      tier: "deluxe", sleeps: 5, suiteSleeps: 0, transport: ["monorail", "boat"], parks: { mk: 3, epcot: 2, hs: 1, ak: 1 },
      access: { mk: "Monorail or boat to Magic Kingdom", epcot: "Walk to the EPCOT monorail" },
      vibes: ["tropical", "lively"], pool: 3, poolNote: "Volcano pool with a waterslide",
      goodFor: ["young-kids", "kids", "grandparents"],
      blurb: "South Pacific theming on the Seven Seas Lagoon, Dole Whip on site, and Magic Kingdom fireworks from the beach." },
    { id: "wl", name: "Wilderness Lodge", sub: "Deluxe resort",
      tier: "deluxe", sleeps: 4, suiteSleeps: 0, transport: ["boat"], parks: { mk: 2, epcot: 1, hs: 1, ak: 1 },
      access: { mk: "Boat to Magic Kingdom" },
      vibes: ["rustic", "nature", "quiet"], pool: 3, poolNote: "Hot-spring-style pool beside an erupting geyser",
      goodFor: ["kids", "adults", "grandparents"],
      blurb: "A Pacific Northwest national-park lodge with its own geyser, a towering lobby and a boat to Magic Kingdom." },

    // Disney Vacation Club villas (bookable with cash as well as points)
    { id: "bay-lake-tower", name: "Bay Lake Tower at the Contemporary", sub: "Disney Vacation Club villas", host: "contemporary",
      tier: "villa", sleeps: 4, suiteSleeps: 12, suiteLabel: "One- to three-bedroom villas", transport: ["monorail", "walk"], parks: { mk: 3, epcot: 2, hs: 1, ak: 1 },
      access: { mk: "Walk or take the monorail to Magic Kingdom", epcot: "Monorail to EPCOT with one transfer" },
      vibes: ["modern"], pool: 2, goodFor: ["kids", "teens", "adults", "grandparents"],
      blurb: "Sleek villas with kitchens next to the Contemporary, a short walk to Magic Kingdom. Many rooms look straight at Cinderella Castle." },
    { id: "akv", name: "Animal Kingdom Villas", sub: "Jambo House and Kidani Village", host: "akl",
      tier: "villa", sleeps: 4, suiteSleeps: 12, suiteLabel: "One- to three-bedroom villas", transport: [], parks: { mk: 1, epcot: 1, hs: 1, ak: 2 },
      access: { ak: "A short bus ride to Animal Kingdom" },
      vibes: ["nature", "quiet"], pool: 2, goodFor: ["young-kids", "kids", "grandparents"],
      blurb: "Villas with kitchens overlooking the savanna. Kidani Village has its own splash area and Sanaa." },
    { id: "beach-club-villas", name: "Beach Club Villas", sub: "Disney Vacation Club villas", host: "beach-club",
      tier: "villa", sleeps: 4, suiteSleeps: 8, suiteLabel: "One- and two-bedroom villas", transport: ["walk", "boat", "skyliner"], parks: { mk: 1, epcot: 3, hs: 3, ak: 1 },
      access: { epcot: "Walk to EPCOT's International Gateway", hs: "Boat or walking path to Hollywood Studios" },
      vibes: ["playful", "elegant"], pool: 3, poolNote: "Access to Stormalong Bay", goodFor: ["kids", "teens", "grandparents"],
      blurb: "Pastel Cape Cod-style villas with kitchens, steps from EPCOT and Stormalong Bay." },
    { id: "boardwalk-villas", name: "BoardWalk Villas", sub: "Disney Vacation Club villas", host: "boardwalk",
      tier: "villa", sleeps: 4, suiteSleeps: 12, suiteLabel: "One- to three-bedroom villas", transport: ["walk", "boat", "skyliner"], parks: { mk: 1, epcot: 3, hs: 3, ak: 1 },
      access: { epcot: "Walk to EPCOT's International Gateway", hs: "Boat or walking path to Hollywood Studios" },
      vibes: ["lively"], pool: 2, goodFor: ["kids", "teens", "adults", "grandparents"],
      blurb: "Villas with kitchens above the BoardWalk promenade, walking distance to two parks." },
    { id: "boulder-ridge", name: "Boulder Ridge Villas at Wilderness Lodge", sub: "Disney Vacation Club villas", host: "wl",
      tier: "villa", sleeps: 4, suiteSleeps: 8, suiteLabel: "One- and two-bedroom villas", transport: ["boat"], parks: { mk: 2, epcot: 1, hs: 1, ak: 1 },
      access: { mk: "Boat to Magic Kingdom" },
      vibes: ["rustic", "quiet"], pool: 2, goodFor: ["kids", "grandparents"],
      blurb: "Railroad-lodge villas with kitchens, sharing Wilderness Lodge's pools, restaurants and boat to Magic Kingdom." },
    { id: "copper-creek", name: "Copper Creek Villas & Cabins", sub: "Disney Vacation Club villas", host: "wl",
      tier: "villa", sleeps: 4, suiteSleeps: 12, suiteLabel: "Villas and waterfront cabins", transport: ["boat"], parks: { mk: 2, epcot: 1, hs: 1, ak: 1 },
      access: { mk: "Boat to Magic Kingdom" },
      vibes: ["rustic", "nature"], pool: 3, poolNote: "Copper Creek Springs pool beside the geyser", goodFor: ["kids", "adults", "grandparents"],
      blurb: "Villas inside Wilderness Lodge and lakefront cabins with private hot tubs." },
    { id: "gf-villas", name: "Villas at the Grand Floridian", sub: "Disney Vacation Club villas", host: "gf",
      tier: "villa", sleeps: 5, suiteSleeps: 12, suiteLabel: "One- to three-bedroom villas", transport: ["monorail", "boat"], parks: { mk: 3, epcot: 2, hs: 1, ak: 1 },
      access: { mk: "One monorail stop to Magic Kingdom", epcot: "Monorail to EPCOT with one transfer" },
      vibes: ["elegant", "quiet"], pool: 3, poolNote: "Alice in Wonderland splash area and beach pool",
      goodFor: ["young-kids", "grandparents"],
      blurb: "Victorian villas with kitchens on the monorail loop, sharing the Grand Floridian's pools and restaurants." },
    { id: "poly-villas", name: "Polynesian Villas & Bungalows", sub: "Including Island Tower", host: "poly",
      tier: "villa", sleeps: 5, suiteSleeps: 8, suiteLabel: "Bungalows and Island Tower two-bedroom villas", transport: ["monorail", "boat"], parks: { mk: 3, epcot: 2, hs: 1, ak: 1 },
      access: { mk: "Monorail or boat to Magic Kingdom", epcot: "Walk to the EPCOT monorail" },
      vibes: ["tropical", "lively"], pool: 3, poolNote: "Volcano pool with a waterslide",
      goodFor: ["young-kids", "kids", "grandparents"],
      blurb: "Studios, overwater bungalows and the newer Island Tower villas on the Seven Seas Lagoon." },
    { id: "okw", name: "Old Key West Resort", sub: "Disney Vacation Club villas",
      tier: "villa", sleeps: 4, suiteSleeps: 12, suiteLabel: "One- to three-bedroom villas", transport: ["boat"], parks: { mk: 1, epcot: 1, hs: 1, ak: 1 },
      vibes: ["tropical", "quiet"], pool: 2, goodFor: ["adults", "grandparents"],
      blurb: "The original Disney Vacation Club resort, with Key West cottages, some of the largest villas on property, and a boat to Disney Springs." },
    { id: "riviera", name: "Riviera Resort", sub: "Disney Vacation Club villas",
      tier: "villa", sleeps: 5, suiteSleeps: 12, suiteLabel: "One- to three-bedroom villas", transport: ["skyliner"], parks: { mk: 1, epcot: 2, hs: 2, ak: 1 },
      access: { epcot: "Skyliner gondola to EPCOT", hs: "Skyliner gondola to Hollywood Studios" },
      vibes: ["elegant", "quiet"], pool: 2, goodFor: ["adults", "grandparents"],
      blurb: "European Riviera-inspired villas with kitchens, its own Skyliner station, and Topolino's Terrace on the rooftop." },
    { id: "saratoga", name: "Saratoga Springs Resort & Spa", sub: "Disney Vacation Club villas",
      tier: "villa", sleeps: 4, suiteSleeps: 12, suiteLabel: "Villas and Treehouse Villas", transport: ["boat"], parks: { mk: 1, epcot: 1, hs: 1, ak: 1 },
      vibes: ["quiet", "elegant"], pool: 2, goodFor: ["adults", "grandparents"],
      blurb: "Upstate New York spa-town villas with a walkway and boat to Disney Springs, plus Treehouse Villas in the woods." },
    { id: "cabins", name: "Cabins at Fort Wilderness", sub: "Disney Vacation Club cabins", host: "fw-campsites", roomLabel: "Cabins",
      tier: "villa", sleeps: 6, suiteSleeps: 0, transport: ["boat"], parks: { mk: 2, epcot: 1, hs: 1, ak: 1 },
      access: { mk: "Boat to Magic Kingdom" },
      vibes: ["rustic", "nature"], pool: 2, goodFor: ["kids", "grandparents"],
      blurb: "Standalone cabins in the pines that sleep six, with a full kitchen, a private deck and a boat to Magic Kingdom." },

    // On Disney property, run by Marriott
    { id: "swan-dolphin", name: "Walt Disney World Swan and Dolphin", sub: "Marriott hotels on Disney property", partner: true,
      tier: "deluxe", sleeps: 4, suiteSleeps: 0, transport: ["walk", "boat", "skyliner"], parks: { mk: 1, epcot: 3, hs: 3, ak: 1 },
      access: { epcot: "Walk to EPCOT's International Gateway", hs: "Boat or walking path to Hollywood Studios" },
      vibes: ["lively", "modern"], pool: 3, poolNote: "Grotto pool with a waterslide", goodFor: ["teens", "adults"],
      blurb: "Walk to EPCOT for less than the Disney-run resorts next door, and earn Marriott points. Disney dining plans aren't available here." },
    { id: "swan-reserve", name: "Walt Disney World Swan Reserve", sub: "Marriott hotel on Disney property", partner: true,
      tier: "deluxe", sleeps: 4, suiteSleeps: 0, transport: ["walk", "boat", "skyliner"], parks: { mk: 1, epcot: 3, hs: 2, ak: 1 },
      access: { epcot: "Walk to EPCOT's International Gateway" },
      vibes: ["quiet", "modern"], pool: 2, goodFor: ["adults"],
      blurb: "A smaller, quieter boutique hotel beside the Swan. Disney dining plans aren't available here." }
  ],

  restaurants: [
    // ---------- Magic Kingdom ----------
    { id: "crt", name: "Cinderella's Royal Table", where: "Magic Kingdom", park: "mk", menu: "magic-kingdom/cinderella-royal-table",
      kind: "character", price: 4, credits: 2, chars: "Cinderella and other princesses", themes: ["princess"],
      picky: 1, adv: 0, kids: 2, adults: 0, celebrate: ["first", "birthday"],
      note: "Dine inside Cinderella Castle. Fixed price, and it books up fast." },
    { id: "bog", name: "Be Our Guest Restaurant", where: "Magic Kingdom", park: "mk", menu: "magic-kingdom/be-our-guest-restaurant",
      kind: "table", price: 4, credits: 2, themes: ["princess"], kids: 1, celebrate: ["first", "anniversary"],
      note: "Dine in the Beast's castle ballroom. The Beast often makes an appearance." },
    { id: "crystal", name: "The Crystal Palace", where: "Magic Kingdom", park: "mk", menu: "magic-kingdom/crystal-palace",
      kind: "character", family: true, price: 3, chars: "Winnie the Pooh, Tigger, Eeyore and Piglet", themes: ["classic"],
      picky: 2, adv: 0, kids: 2, adults: 0,
      note: "Buffet in a bright Victorian glass conservatory." },
    { id: "plaza", name: "The Plaza Restaurant", where: "Magic Kingdom", park: "mk", menu: "magic-kingdom/plaza-restaurant",
      kind: "table", price: 2, picky: 2, adv: 0, kids: 2, celebrate: ["birthday"],
      note: "Burgers, sandwiches and giant sundaes at the end of Main Street, U.S.A." },
    { id: "tonys", name: "Tony's Town Square Restaurant", where: "Magic Kingdom", park: "mk", menu: "magic-kingdom/tonys-town-square-restaurant",
      kind: "table", price: 3, themes: ["classic"], picky: 2, adv: 0, kids: 2,
      note: "Lady and the Tramp-themed Italian on Town Square." },
    { id: "liberty", name: "Liberty Tree Tavern", where: "Magic Kingdom", park: "mk", menu: "magic-kingdom/liberty-tree-tavern",
      kind: "table", family: true, price: 3, picky: 2, adv: 0,
      note: "An all-you-care-to-enjoy Thanksgiving-style feast served family-style." },
    { id: "skipper", name: "Jungle Navigation Co. LTD Skipper Canteen", where: "Magic Kingdom", park: "mk", menu: "magic-kingdom/jungle-navigation-skipper-canteen",
      kind: "table", price: 3, themes: ["animals"], adv: 2,
      note: "Jungle Cruise skippers serve bad puns alongside globally inspired dishes." },
    { id: "diamond-horseshoe", name: "The Diamond Horseshoe", where: "Magic Kingdom", park: "mk",
      kind: "table", price: 3, credits: null, picky: 2, adv: 0, kids: 2, status: "Limited-time dining from October 4, 2026",
      note: "A Frontierland saloon serving ribs, corn fritters and mini corn dogs." },
    { id: "columbia", name: "Columbia Harbour House", where: "Magic Kingdom", park: "mk", menu: "magic-kingdom/columbia-harbour-house",
      kind: "quick", price: 1, picky: 2, adv: 0, kids: 2,
      note: "Fried fish, shrimp, lobster rolls and chicken nuggets, with quiet seating upstairs." },
    { id: "pecos", name: "Pecos Bill Tall Tale Inn and Cafe", where: "Magic Kingdom", park: "mk", menu: "magic-kingdom/pecos-bill-tall-tale-inn-and-cafe",
      kind: "quick", price: 1, picky: 1,
      note: "Burritos, fajitas and rice bowls with a toppings bar in Frontierland." },
    { id: "cosmic", name: "Cosmic Ray's Starlight Cafe", where: "Magic Kingdom", park: "mk", menu: "magic-kingdom/cosmic-ray-starlight-cafe",
      kind: "quick", price: 1, themes: ["starwars"], picky: 2, adv: 0, kids: 2,
      note: "Burgers, chicken and ribs, with an alien lounge singer entertaining the dining room." },
    { id: "pinocchio", name: "Pinocchio Village Haus", where: "Magic Kingdom", park: "mk", menu: "magic-kingdom/pinocchio-village-haus",
      kind: "quick", price: 1, themes: ["classic"], picky: 2, adv: 0, kids: 2,
      note: "Flatbread pizzas and pasta in Fantasyland. Some tables overlook “it's a small world.”" },
    { id: "caseys", name: "Casey's Corner", where: "Magic Kingdom", park: "mk",
      kind: "quick", price: 1, picky: 2, adv: 0, kids: 2,
      note: "Ballpark hot dogs and corn dog nuggets on Main Street, U.S.A." },
    { id: "tomorrowland-terrace", name: "Tomorrowland Terrace Restaurant", where: "Magic Kingdom", park: "mk",
      kind: "quick", price: 1, picky: 2, adv: 0, kids: 2, status: "Open seasonally",
      note: "Burgers and sandwiches with a view of Cinderella Castle." },
    { id: "friars-nook", name: "The Friar's Nook", where: "Magic Kingdom", park: "mk",
      kind: "quick", price: 1, picky: 2, adv: 0, kids: 2,
      note: "Mac and cheese bowls and hot dogs in Fantasyland." },

    // ---------- EPCOT ----------
    { id: "akershus", name: "Akershus Royal Banquet Hall", where: "EPCOT – Norway", park: "epcot", menu: "epcot/akershus-royal-banquet-hall",
      kind: "character", family: true, price: 3, credits: 2, creditsNote: "1 at breakfast",
      chars: "Belle, Ariel, Snow White and other princesses (lineup varies)", themes: ["princess"],
      kids: 2, adults: 0, celebrate: ["first", "birthday"],
      note: "Princess dining that is usually easier to book than Cinderella's Royal Table." },
    { id: "garden-grill", name: "Garden Grill Restaurant", where: "EPCOT – The Land", park: "epcot", menu: "epcot/garden-grill-restaurant",
      kind: "character", family: true, price: 3, chars: "Chip, Dale, Mickey and Pluto in farm outfits", themes: ["classic"],
      picky: 2, adv: 0, kids: 2,
      note: "A slowly rotating dining room that passes scenes from Living with the Land." },
    { id: "coral-reef", name: "Coral Reef Restaurant", where: "EPCOT – The Seas", park: "epcot", menu: "epcot/coral-reef-restaurant",
      kind: "table", price: 3, themes: ["animals"], kids: 2, status: "Reopening fall 2026 after a refurbishment",
      note: "Seafood beside a giant aquarium full of sharks, rays and sea turtles." },
    { id: "space220", name: "Space 220 Restaurant", where: "EPCOT – Mission: SPACE", park: "epcot", menu: "epcot/space-220",
      kind: "signature", price: 4, credits: 0, themes: ["starwars"], kids: 2, celebrate: ["birthday"],
      note: "Ride a space elevator to a dining room with a view of Earth from orbit." },
    { id: "le-cellier", name: "Le Cellier Steakhouse", where: "EPCOT – Canada", park: "epcot", menu: "epcot/le-cellier-steakhouse",
      kind: "signature", price: 4, kids: 0, adults: 2, celebrate: ["anniversary"],
      note: "Filet mignon and cheddar cheese soup in a cozy stone wine cellar." },
    { id: "via-napoli", name: "Via Napoli Ristorante e Pizzeria", where: "EPCOT – Italy", park: "epcot", menu: "epcot/via-napoli",
      kind: "table", price: 3, picky: 2, adv: 0, kids: 2,
      note: "Wood-fired Neapolitan pizza, including a half-meter pizza for the table." },
    { id: "tutto-italia", name: "Tutto Italia Ristorante", where: "EPCOT – Italy", park: "epcot", menu: "epcot/tutto-italia-ristorante",
      kind: "table", price: 3, adults: 2, celebrate: ["anniversary"],
      note: "Classic Italian pastas in an elegant Roman-style dining room." },
    { id: "biergarten", name: "Biergarten Restaurant", where: "EPCOT – Germany", park: "epcot", menu: "epcot/biergarten-restaurant",
      kind: "table", family: true, price: 3, adv: 1, adults: 2,
      note: "A German buffet in a Bavarian village square, with an oompah band." },
    { id: "teppan-edo", name: "Teppan Edo", where: "EPCOT – Japan", park: "epcot", menu: "epcot/teppan-edo",
      kind: "table", price: 3, picky: 2, kids: 2, celebrate: ["birthday"],
      note: "Hibachi chefs cook at your table. Great for teens." },
    { id: "shiki-sai", name: "Shiki-Sai: Sushi Izakaya", where: "EPCOT – Japan", park: "epcot",
      kind: "table", price: 3, picky: 0, adv: 2, adults: 2,
      note: "Sushi and Japanese small plates in a dining room with changing seasonal scenery." },
    { id: "takumi-tei", name: "Takumi-Tei", where: "EPCOT – Japan", park: "epcot", menu: "epcot/takumi-tei-restaurant",
      kind: "signature", price: 4, credits: 0, picky: 0, adv: 2, kids: 0, adults: 2, celebrate: ["anniversary"],
      note: "Multi-course omakase tasting menus in a serene dining room." },
    { id: "nine-dragons", name: "Nine Dragons Restaurant", where: "EPCOT – China", park: "epcot", menu: "epcot/nine-dragons-restaurant",
      kind: "table", price: 2,
      note: "Regional Chinese dishes, dumplings and bao buns." },
    { id: "san-angel-inn", name: "San Angel Inn Restaurante", where: "EPCOT – Mexico", park: "epcot", menu: "epcot/san-angel-inn-restaurante",
      kind: "table", price: 3, adults: 2, celebrate: ["anniversary"],
      note: "Dine in perpetual twilight beside a smoking volcano inside the Mexico pyramid." },
    { id: "hacienda", name: "La Hacienda de San Angel", where: "EPCOT – Mexico", park: "epcot", menu: "epcot/hacienda-de-san-angel",
      kind: "table", price: 3, adults: 2,
      note: "Tacos and margaritas with lagoon views. Great for watching the nighttime show." },
    { id: "chefs-de-france", name: "Chefs de France", where: "EPCOT – France", park: "epcot", menu: "epcot/chefs-de-france",
      kind: "table", price: 3, adults: 2,
      note: "A Parisian brasserie serving French onion soup, croque monsieur and crème brûlée." },
    { id: "monsieur-paul", name: "Monsieur Paul", where: "EPCOT – France", park: "epcot", menu: "epcot/monsieur-paul",
      kind: "signature", price: 4, credits: 0, picky: 0, adv: 2, kids: 0, adults: 2, celebrate: ["anniversary"],
      note: "Formal French fine dining above Chefs de France." },
    { id: "spice-road", name: "Spice Road Table", where: "EPCOT – Morocco", park: "epcot", menu: "epcot/spice-road-table",
      kind: "table", price: 2, adv: 2, adults: 2,
      note: "Mediterranean small plates on the water. A top spot for watching the nighttime show." },
    { id: "rose-crown", name: "Rose & Crown Dining Room", where: "EPCOT – United Kingdom", park: "epcot", menu: "epcot/rose-and-crown-dining-room",
      kind: "table", price: 3, picky: 2, adults: 2,
      note: "Fish and chips and shepherd's pie in a British pub, with lagoon-side patio seating." },
    { id: "sunshine-seasons", name: "Sunshine Seasons", where: "EPCOT – The Land", park: "epcot", menu: "epcot/sunshine-seasons",
      kind: "quick", price: 1, kids: 2,
      note: "A food court with rotisserie meats, salads and bowls, using produce grown in The Land." },
    { id: "regal-eagle", name: "Regal Eagle Smokehouse", where: "EPCOT – The American Adventure", park: "epcot", menu: "epcot/regal-eagle-smokehouse",
      kind: "quick", price: 2, picky: 2, adv: 0, kids: 2,
      note: "Barbecue from around the country, with a fixin's bar." },
    { id: "connections", name: "Connections Eatery", where: "EPCOT – World Celebration", park: "epcot",
      kind: "quick", price: 1, picky: 2, adv: 0, kids: 2,
      note: "Burgers and pizza in a bright, modern dining hall." },
    { id: "katsura", name: "Katsura Grill", where: "EPCOT – Japan", park: "epcot", menu: "epcot/katsura-grill",
      kind: "quick", price: 2, adv: 2,
      note: "Teriyaki, sushi, curry and udon beside a quiet Japanese garden." },
    { id: "lotus-blossom", name: "Lotus Blossom Café", where: "EPCOT – China", park: "epcot",
      kind: "quick", price: 1,
      note: "Orange chicken, fried rice and potstickers." },
    { id: "sommerfest", name: "Sommerfest", where: "EPCOT – Germany", park: "epcot",
      kind: "quick", price: 1, adults: 2,
      note: "Bratwurst, soft pretzels and German beer." },
    { id: "la-cantina", name: "La Cantina de San Angel", where: "EPCOT – Mexico", park: "epcot",
      kind: "quick", price: 1,
      note: "Tacos, empanadas and churros on the lagoon." },
    { id: "les-halles", name: "Les Halles Boulangerie-Patisserie", where: "EPCOT – France", park: "epcot", menu: "epcot/les-halles-boulangerie-patisserie",
      kind: "quick", price: 1, adults: 2,
      note: "French baguette sandwiches, quiche and pastries." },
    { id: "tangierine", name: "Tangierine Café: Flavors of the Medina", where: "EPCOT – Morocco", park: "epcot", menu: "epcot/tangierine-cafe",
      kind: "quick", price: 2, adv: 2,
      note: "Shawarma platters, hummus and baklava." },
    { id: "yorkshire", name: "Yorkshire County Fish Shop", where: "EPCOT – United Kingdom", park: "epcot", menu: "epcot/yorkshire-county-fish-shop",
      kind: "quick", price: 1, picky: 2, adv: 0,
      note: "Fish and chips and shortbread." },
    { id: "kringla", name: "Kringla Bakeri og Kafé", where: "EPCOT – Norway", park: "epcot", menu: "epcot/kringla-bakeri-og-kafe",
      kind: "quick", price: 1,
      note: "Norwegian pastries, including the famous School Bread, and open-faced sandwiches." },
    { id: "la-poutinerie", name: "La Poutinerie", where: "EPCOT – Canada", park: "epcot",
      kind: "quick", price: 1, picky: 2, adv: 0, status: "New in July 2026",
      note: "Canadian poutine with a variety of toppings." },

    // ---------- Hollywood Studios ----------
    { id: "hollywood-vine", name: "Hollywood & Vine", where: "Hollywood Studios", park: "hs",
      kind: "character", family: true, price: 3, chars: "Disney Junior pals at breakfast; Minnie and friends at dinner", themes: ["classic"],
      picky: 2, adv: 0, kids: 2, adults: 0,
      note: "Buffet with seasonal themes at dinner." },
    { id: "brown-derby", name: "The Hollywood Brown Derby", where: "Hollywood Studios", park: "hs", menu: "hollywood-studios/hollywood-brown-derby",
      kind: "signature", price: 4, kids: 0, adults: 2, celebrate: ["anniversary"],
      note: "Old Hollywood glamour and the original Cobb salad." },
    { id: "prime-time", name: "50's Prime Time Café", where: "Hollywood Studios", park: "hs", menu: "hollywood-studios/50s-prime-time-cafe",
      kind: "table", price: 3, picky: 2, adv: 0, kids: 2,
      note: "Comfort food in a 1950s kitchen, where your server makes sure you finish your vegetables." },
    { id: "sci-fi", name: "Sci-Fi Dine-In Theater Restaurant", where: "Hollywood Studios", park: "hs", menu: "hollywood-studios/sci-fi-dine-in-theater",
      kind: "table", price: 2, themes: ["starwars"], picky: 2, adv: 0, kids: 2,
      note: "Eat in a vintage car at a drive-in while old sci-fi trailers play." },
    { id: "roundup-rodeo", name: "Roundup Rodeo BBQ", where: "Hollywood Studios – Toy Story Land", park: "hs", menu: "hollywood-studios/roundup-rodeo-bbq",
      kind: "table", family: true, price: 3, themes: ["pixar"], picky: 2, adv: 0, kids: 2, celebrate: ["birthday"],
      note: "All-you-care-to-enjoy barbecue platters in Andy's backyard rodeo." },
    { id: "docking-bay", name: "Docking Bay 7 Food and Cargo", where: "Hollywood Studios – Galaxy's Edge", park: "hs", menu: "hollywood-studios/docking-bay-7-food-and-cargo",
      kind: "quick", price: 2, themes: ["starwars"],
      note: "Galactic comfort food inside Star Wars: Galaxy's Edge." },
    { id: "ronto", name: "Ronto Roasters", where: "Hollywood Studios – Galaxy's Edge", park: "hs", menu: "hollywood-studios/ronto-roasters",
      kind: "quick", price: 1, themes: ["starwars"],
      note: "The Ronto Wrap: grilled sausage and roast pork in pita, cooked beside a podracer engine." },
    { id: "woodys", name: "Woody's Lunch Box", where: "Hollywood Studios – Toy Story Land", park: "hs", menu: "hollywood-studios/woodys-lunchbox",
      kind: "quick", price: 1, themes: ["pixar"], picky: 2, adv: 0, kids: 2,
      note: "Grilled cheese, totchos and lunch box tarts." },
    { id: "backlot", name: "Backlot Express", where: "Hollywood Studios", park: "hs", menu: "hollywood-studios/backlot-express",
      kind: "quick", price: 1, picky: 2, adv: 0, kids: 2,
      note: "Burgers and bowls in a movie prop warehouse." },
    { id: "abc-commissary", name: "ABC Commissary", where: "Hollywood Studios", park: "hs", menu: "hollywood-studios/abc-commissary",
      kind: "quick", price: 1,
      note: "Sandwiches, bowls and tacos in an Art Deco studio commissary." },
    { id: "rosies", name: "Rosie's All-American Café", where: "Hollywood Studios", park: "hs", menu: "hollywood-studios/rosies-all-american-cafe",
      kind: "quick", price: 1, picky: 2, adv: 0, kids: 2,
      note: "Burgers, chicken nuggets and fries on Sunset Boulevard." },
    { id: "fairfax", name: "Fairfax Fare", where: "Hollywood Studios", park: "hs", menu: "hollywood-studios/fairfax-fare",
      kind: "quick", price: 1,
      note: "Barbecue and rice bowls on Sunset Boulevard." },

    // ---------- Animal Kingdom ----------
    { id: "tusker", name: "Tusker House Restaurant", where: "Animal Kingdom", park: "ak", menu: "animal-kingdom/tusker-house-restaurant",
      kind: "character", family: true, price: 3, chars: "Mickey, Donald, Daisy and Goofy in safari gear", themes: ["classic", "animals"],
      picky: 2, kids: 2,
      note: "African-inspired family-style meal with plenty of familiar dishes." },
    { id: "tiffins", name: "Tiffins Restaurant", where: "Animal Kingdom", park: "ak", menu: "animal-kingdom/tiffins",
      kind: "signature", price: 4, themes: ["animals"], picky: 0, adv: 2, kids: 0, adults: 2, celebrate: ["anniversary"],
      note: "Global flavors inspired by the Imagineers' travels, in galleries of their artwork." },
    { id: "yak-yeti", name: "Yak & Yeti Restaurant", where: "Animal Kingdom – Asia", park: "ak",
      kind: "table", price: 3, credits: null, themes: ["animals"],
      note: "Pan-Asian dishes in a two-story Himalayan setting." },
    { id: "rainforest-ak", name: "Rainforest Cafe", where: "Animal Kingdom entrance", park: "ak", menu: "animal-kingdom/rainforest-cafe-animal-kingdom",
      kind: "table", price: 3, credits: null, themes: ["animals"], picky: 2, adv: 0, kids: 2, adults: 0, celebrate: ["birthday"],
      note: "Animatronic animals, thunderstorms and big portions." },
    { id: "satuli", name: "Satu'li Canteen", where: "Animal Kingdom – Pandora", park: "ak", menu: "animal-kingdom/satuli-canteen",
      kind: "quick", price: 2, themes: ["animals"], adults: 2,
      note: "Build-your-own bowls inside Pandora – The World of Avatar." },
    { id: "flame-tree", name: "Flame Tree Barbecue", where: "Animal Kingdom", park: "ak",
      kind: "quick", price: 2, picky: 2, adv: 0,
      note: "Smoked ribs and pulled pork with shaded waterfront seating." },
    { id: "harambe-market", name: "Harambe Market", where: "Animal Kingdom – Africa", park: "ak", menu: "animal-kingdom/harambe-market",
      kind: "quick", price: 2, themes: ["animals"], adv: 2,
      note: "African-inspired dishes from open-air market windows. Reopened in 2026." },
    { id: "yak-yeti-local", name: "Yak & Yeti Local Food Cafes", where: "Animal Kingdom – Asia", park: "ak",
      kind: "quick", price: 1, credits: null,
      note: "Orange chicken, egg rolls and teriyaki at a walk-up counter." },

    // ---------- Contemporary ----------
    { id: "chef-mickeys", name: "Chef Mickey's", where: "Contemporary Resort", park: "resort", resort: "contemporary", menu: "contemporary-resort/chef-mickeys",
      kind: "character", family: true, price: 3, chars: "Mickey, Minnie, Donald, Goofy and Pluto", themes: ["classic"],
      picky: 2, adv: 0, kids: 2, adults: 0,
      note: "A lively buffet with the monorail gliding overhead." },
    { id: "california-grill", name: "California Grill", where: "Contemporary Resort", park: "resort", resort: "contemporary", menu: "contemporary-resort/california-grill",
      kind: "signature", price: 4, credits: 0, picky: 0, kids: 0, adults: 2, celebrate: ["anniversary"],
      note: "Top-floor dining with Magic Kingdom fireworks viewing from the observation deck." },
    { id: "steakhouse-71", name: "Steakhouse 71", where: "Contemporary Resort", park: "resort", resort: "contemporary", menu: "contemporary-resort/steakhouse-71",
      kind: "table", price: 3, adults: 2,
      note: "A mid-century steakhouse named for the year Walt Disney World opened." },
    { id: "contempo", name: "Contempo Cafe", where: "Contemporary Resort", park: "resort", resort: "contemporary", menu: "contemporary-resort/contempo-cafe",
      kind: "quick", price: 1, picky: 2, adv: 0,
      note: "Flatbreads, sandwiches and breakfast platters." },

    // ---------- Polynesian ----------
    { id: "ohana", name: "'Ohana", where: "Polynesian Village Resort", park: "resort", resort: "poly", menu: "polynesian-resort/ohana",
      kind: "character", family: true, price: 3, chars: "Breakfast only: Lilo, Stitch, Mickey and Pluto", themes: ["classic"],
      picky: 2, kids: 2,
      note: "Family-style skewers, noodles and bread pudding at dinner." },
    { id: "kona", name: "Kona Cafe", where: "Polynesian Village Resort", park: "resort", resort: "poly", menu: "polynesian-resort/kona-cafe",
      kind: "table", price: 2,
      note: "Famous for Tonga Toast at breakfast and Pan-Asian dishes later in the day." },
    { id: "capt-cooks", name: "Capt. Cook's", where: "Polynesian Village Resort", park: "resort", resort: "poly",
      kind: "quick", price: 1, picky: 2, adv: 0, kids: 2,
      note: "Island-inspired quick bites, plus Dole Whip." },

    // ---------- Grand Floridian ----------
    { id: "park-fare", name: "1900 Park Fare", where: "Grand Floridian Resort", park: "resort", resort: "gf",
      kind: "character", family: true, price: 3, chars: "Cinderella, her stepfamily and friends (lineup varies by meal)", themes: ["princess", "classic"],
      picky: 2, adv: 0, kids: 2, adults: 0, celebrate: ["first", "birthday"],
      note: "Buffet in a bright Victorian dining room." },
    { id: "citricos", name: "Cítricos", where: "Grand Floridian Resort", park: "resort", resort: "gf",
      kind: "signature", price: 4, picky: 0, adv: 2, kids: 0, adults: 2, celebrate: ["anniversary"],
      note: "Mediterranean-inspired signature dining with an open kitchen." },
    { id: "narcoossees", name: "Narcoossee's", where: "Grand Floridian Resort", park: "resort", resort: "gf", menu: "grand-floridian-resort-and-spa/narcoossees",
      kind: "signature", price: 4, picky: 0, adv: 1, kids: 0, adults: 2, celebrate: ["anniversary"],
      note: "Waterfront seafood with Magic Kingdom fireworks across the lagoon." },
    { id: "vanda", name: "Victoria & Albert's", where: "Grand Floridian Resort", park: "resort", resort: "gf",
      kind: "signature", price: 4, credits: 0, picky: 0, adv: 2, kids: 0, adults: 2, minAge: 10, celebrate: ["anniversary"],
      menuUrl: "https://disneyworld.disney.go.com/dining/victoria-and-alberts-overview/",
      note: "A multi-course tasting menu and Disney's most formal dining. Guests must be 10 or older." },
    { id: "gf-cafe", name: "Grand Floridian Cafe", where: "Grand Floridian Resort", park: "resort", resort: "gf", menu: "grand-floridian-resort-and-spa/grand-floridian-cafe",
      kind: "table", price: 3, picky: 2, status: "Closed for refurbishment until about October 2026",
      note: "Relaxed Southern-inspired comfort food in a garden-view dining room." },
    { id: "gasparilla", name: "Gasparilla Island Grill", where: "Grand Floridian Resort", park: "resort", resort: "gf", menu: "grand-floridian-resort-and-spa/gasparilla-island-grill",
      kind: "quick", price: 1, picky: 2, adv: 0,
      note: "Burgers, flatbreads and breakfast platters by the pool." },

    // ---------- Wilderness Lodge ----------
    { id: "storybook", name: "Story Book Dining at Artist Point", where: "Wilderness Lodge", park: "resort", resort: "wl",
      kind: "character", price: 4, credits: 2, chars: "Snow White, Dopey, Grumpy and the Evil Queen", themes: ["princess"],
      kids: 1, adults: 1,
      note: "Dinner only, with a fixed-price menu inspired by the enchanted forest." },
    { id: "whispering-canyon", name: "Whispering Canyon Cafe", where: "Wilderness Lodge", park: "resort", resort: "wl", menu: "wilderness-lodge-resort/whispering-canyon-cafe",
      kind: "table", family: true, price: 3, picky: 2, adv: 0, kids: 2, celebrate: ["birthday"],
      note: "All-you-care-to-enjoy skillets served with plenty of Wild West sass. Ask for ketchup." },
    { id: "roaring-fork", name: "Roaring Fork", where: "Wilderness Lodge", park: "resort", resort: "wl",
      kind: "quick", price: 1, picky: 2, adv: 0,
      note: "Breakfast platters and sandwiches next to the pool." },
    { id: "geyser-point", name: "Geyser Point Bar & Grill", where: "Wilderness Lodge", park: "resort", resort: "wl", menu: "wilderness-lodge-resort/geyser-point",
      kind: "quick", price: 2, adults: 2,
      note: "Lakeside counter service with bison burgers and views of Bay Lake." },

    // ---------- Fort Wilderness ----------
    { id: "hoop-dee-doo", name: "Hoop-Dee-Doo Musical Revue", where: "Fort Wilderness", park: "resort", resort: "fw-campsites",
      kind: "table", family: true, price: 4, credits: 2, picky: 2, adv: 0, kids: 2, celebrate: ["birthday", "first"],
      note: "A Wild West dinner show with fried chicken, ribs and strawberry shortcake served family-style." },
    { id: "trails-end", name: "Trail's End Restaurant", where: "Fort Wilderness", park: "resort", resort: "fw-campsites",
      kind: "table", price: 2, picky: 2, adv: 0,
      note: "Country cooking in a log cabin, including fried chicken." },
    { id: "pjs", name: "P&J's Southern Takeout", where: "Fort Wilderness", park: "resort", resort: "fw-campsites", menu: "cabins-at-fort-wilderness-resort/p-and-js-southern-takeout",
      kind: "quick", price: 1, picky: 2, adv: 0,
      note: "Southern-style breakfast and fried chicken to go." },

    // ---------- Beach Club and Yacht Club ----------
    { id: "cape-may", name: "Cape May Cafe", where: "Beach Club Resort", park: "resort", resort: "beach-club", menu: "beach-club-resort/cape-may-cafe",
      kind: "character", family: true, price: 3, chars: "Breakfast: Minnie, Daisy, Donald and Goofy in beachwear", themes: ["classic"],
      picky: 2, adv: 0, kids: 2, adults: 0,
      note: "A relaxed character breakfast, and a seafood buffet at dinner." },
    { id: "beaches-cream", name: "Beaches & Cream Soda Shop", where: "Beach Club Resort", park: "resort", resort: "beach-club",
      kind: "table", price: 2, picky: 2, adv: 0, kids: 2, celebrate: ["birthday"],
      note: "Burgers, shakes and the Kitchen Sink sundae for the whole table." },
    { id: "beach-club-marketplace", name: "Beach Club Marketplace", where: "Beach Club Resort", park: "resort", resort: "beach-club", menu: "beach-club-resort/beach-club-marketplace",
      kind: "quick", price: 1,
      note: "Sandwiches, salads and breakfast to go." },
    { id: "yachtsman", name: "Yachtsman Steakhouse", where: "Yacht Club Resort", park: "resort", resort: "yacht-club", menu: "yacht-club-resort/yachtsman-steakhouse",
      kind: "signature", price: 4, kids: 0, adults: 2, celebrate: ["anniversary"],
      note: "A classic steakhouse with dry-aged steaks and fresh seafood." },
    { id: "ale-compass", name: "Ale & Compass Restaurant", where: "Yacht Club Resort", park: "resort", resort: "yacht-club", menu: "yacht-club-resort/ale-and-compass",
      kind: "table", price: 2,
      note: "New England comfort food, from lobster rolls to crab-cake Benedict." },

    // ---------- BoardWalk ----------
    { id: "flying-fish", name: "Flying Fish", where: "BoardWalk", park: "resort", resort: "boardwalk",
      kind: "signature", price: 4, picky: 0, adv: 2, kids: 0, adults: 2, celebrate: ["anniversary"],
      note: "Inventive seafood and one of the most popular signature restaurants on property." },
    { id: "trattoria", name: "Trattoria al Forno", where: "BoardWalk", park: "resort", resort: "boardwalk", menu: "boardwalk/trattoria-al-forno",
      kind: "table", price: 3,
      note: "Italian comfort food and wood-fired pizza. Character breakfast has ended." },
    { id: "boardwalk-deli", name: "BoardWalk Deli", where: "BoardWalk", park: "resort", resort: "boardwalk",
      kind: "quick", price: 1,
      note: "Sandwiches, pastries and coffee on the promenade." },

    // ---------- Animal Kingdom Lodge ----------
    { id: "boma", name: "Boma – Flavors of Africa", where: "Animal Kingdom Lodge", park: "resort", resort: "akl", menu: "animal-kingdom-lodge/boma-flavors-of-africa",
      kind: "table", family: true, price: 3, themes: ["animals"], adv: 2,
      note: "A buffet of African-inspired dishes next to familiar favorites." },
    { id: "jiko", name: "Jiko – The Cooking Place", where: "Animal Kingdom Lodge", park: "resort", resort: "akl",
      kind: "signature", price: 4, themes: ["animals"], picky: 0, adv: 2, kids: 0, adults: 2, celebrate: ["anniversary"],
      note: "African-inspired signature dining with an award-winning South African wine list." },
    { id: "sanaa", name: "Sanaa", where: "Animal Kingdom Villas – Kidani Village", park: "resort", resort: "akl",
      kind: "table", price: 2, themes: ["animals"], adv: 2, adults: 2,
      note: "Indian-inspired dishes with savanna views. Order the bread service." },
    { id: "the-mara", name: "The Mara", where: "Animal Kingdom Lodge", park: "resort", resort: "akl",
      kind: "quick", price: 1, picky: 2,
      note: "African and American favorites by the pool." },

    // ---------- Other resorts ----------
    { id: "toledo", name: "Toledo – Tapas, Steak & Seafood", where: "Coronado Springs Resort", park: "resort", resort: "coronado", menu: "coronado-springs-resort/toledo",
      kind: "signature", price: 4, picky: 0, kids: 0, adults: 2, celebrate: ["anniversary"],
      note: "Rooftop Spanish-inspired dining on top of the Gran Destino Tower." },
    { id: "three-bridges", name: "Three Bridges Bar & Grill", where: "Coronado Springs Resort", park: "resort", resort: "coronado",
      kind: "table", price: 3, adults: 2,
      note: "Latin-inspired grill on an island in the middle of Lago Dorado." },
    { id: "el-mercado", name: "El Mercado de Coronado", where: "Coronado Springs Resort", park: "resort", resort: "coronado",
      kind: "quick", price: 1,
      note: "Food court with tacos, pizza and burgers." },
    { id: "sebastians", name: "Sebastian's Bistro", where: "Caribbean Beach Resort", park: "resort", resort: "cbr", menu: "caribbean-beach-resort/sebastians-bistro",
      kind: "table", price: 2,
      note: "Caribbean-inspired dinner with a relaxed island feel." },
    { id: "centertown", name: "Centertown Market", where: "Caribbean Beach Resort", park: "resort", resort: "cbr",
      kind: "quick", price: 1, picky: 2, adv: 0,
      note: "Food court with bowls, pizza and burgers." },
    { id: "topolino", name: "Topolino's Terrace – Flavors of the Riviera", where: "Riviera Resort", park: "resort", resort: "riviera", menu: "riviera-resort/topolinos-terrace",
      kind: "character", price: 4, credits: 2, creditsNote: "1 at the character breakfast",
      chars: "Breakfast: Mickey, Minnie, Donald and Daisy in artist outfits", themes: ["classic"],
      adults: 2, celebrate: ["anniversary"],
      note: "Rooftop views. Character breakfast in the morning, French and Italian signature dinner at night." },
    { id: "primo-piatto", name: "Primo Piatto", where: "Riviera Resort", park: "resort", resort: "riviera",
      kind: "quick", price: 1,
      note: "Italian-inspired counter service with flatbreads and pasta." },
    { id: "turf-club", name: "The Turf Club Bar & Grill", where: "Saratoga Springs Resort", park: "resort", resort: "saratoga",
      kind: "table", price: 3, adults: 2, status: "Reopening September 30, 2026",
      note: "A horse-racing-themed grill overlooking the golf course." },
    { id: "artists-palette", name: "The Artist's Palette", where: "Saratoga Springs Resort", park: "resort", resort: "saratoga", menu: "saratoga-springs-resort-and-spa/artists-palette",
      kind: "quick", price: 1,
      note: "Flatbreads, sandwiches and breakfast in an artist's studio." },
    { id: "olivias", name: "Olivia's Cafe", where: "Old Key West Resort", park: "resort", resort: "okw",
      kind: "table", price: 2, picky: 2,
      note: "Key West comfort food in a laid-back island setting." },
    { id: "boatwrights", name: "Boatwright's Dining Hall", where: "Port Orleans – Riverside", park: "resort", resort: "por", menu: "port-orleans-resort-riverside/boatwright-dining-hall",
      kind: "table", price: 3, adv: 1,
      note: "Cajun and Southern dishes in a boat-building workshop." },
    { id: "riverside-mill", name: "Riverside Mill Food Court", where: "Port Orleans – Riverside", park: "resort", resort: "por", menu: "port-orleans-resort-riverside/riverside-mill-food-court",
      kind: "quick", price: 1, picky: 2, adv: 0,
      note: "Food court with a carving station and bakery." },
    { id: "sassagoula", name: "Sassagoula Floatworks and Food Factory", where: "Port Orleans – French Quarter", park: "resort", resort: "pofq", menu: "port-orleans-resort-french-quarter/sassagoula-floatworks-and-food-factory",
      kind: "quick", price: 1, picky: 2,
      note: "Food court famous for its Mickey-shaped beignets." },
    { id: "everything-pop", name: "Everything POP Shopping & Dining", where: "Pop Century Resort", park: "resort", resort: "pop",
      kind: "quick", price: 1, picky: 2, adv: 0, kids: 2,
      note: "Food court with burgers, pizza and breakfast platters." },
    { id: "landscape-of-flavors", name: "Landscape of Flavors", where: "Art of Animation Resort", park: "resort", resort: "aoa", menu: "art-of-animation-resort/landscape-of-flavors",
      kind: "quick", price: 1, picky: 2, adv: 0, kids: 2,
      note: "Food court with burgers, pizza and made-to-order bowls." },
    { id: "world-premiere", name: "World Premiere Food Court", where: "All-Star Movies Resort", park: "resort", resort: "all-star-movies",
      kind: "quick", price: 1, picky: 2, adv: 0, kids: 2,
      note: "Food court with pizza, burgers and breakfast platters." },
    { id: "intermission", name: "Intermission Food Court", where: "All-Star Music Resort", park: "resort", resort: "all-star-music", menu: "all-star-music-resort/intermission-food-court",
      kind: "quick", price: 1, picky: 2, adv: 0, kids: 2,
      note: "Food court with pizza, burgers and breakfast platters." },
    { id: "end-zone", name: "End Zone Food Court", where: "All-Star Sports Resort", park: "resort", resort: "all-star-sports",
      kind: "quick", price: 1, picky: 2, adv: 0, kids: 2,
      note: "Food court with pizza, burgers and breakfast platters." },

    // ---------- Disney Springs ----------
    { id: "homecomin", name: "Chef Art Smith's Homecomin'", where: "Disney Springs", park: "springs",
      kind: "table", price: 3, credits: null, picky: 2, adv: 0, adults: 2,
      note: "Southern comfort food, famous for its fried chicken and hummingbird cake." },
    { id: "boathouse", name: "The BOATHOUSE", where: "Disney Springs", park: "springs", menu: "disney-springs/boathouse-restaurant",
      kind: "table", price: 4, credits: null, adults: 2, celebrate: ["anniversary"],
      note: "Waterfront steaks and seafood, with rides in vintage amphicar boats nearby." },
    { id: "raglan", name: "Raglan Road Irish Pub and Restaurant", where: "Disney Springs", park: "springs",
      kind: "table", price: 3, credits: null, adults: 2,
      note: "Modern Irish food with live music and Irish dancers most evenings." },
    { id: "paddlefish", name: "Paddlefish", where: "Disney Springs", park: "springs", menu: "disney-springs/paddlefish",
      kind: "table", price: 4, credits: null, adults: 2,
      note: "Seafood aboard a stationary paddlewheel boat, with a rooftop lounge." },
    { id: "stk", name: "STK Steakhouse", where: "Disney Springs", park: "springs",
      kind: "table", price: 4, credits: null, kids: 0, adults: 2, celebrate: ["anniversary"],
      note: "A lively, modern steakhouse with a DJ and rooftop terrace." },
    { id: "morimoto", name: "Morimoto Asia", where: "Disney Springs", park: "springs",
      kind: "table", price: 3, credits: null, adv: 2, adults: 2,
      note: "Pan-Asian dishes from Iron Chef Masaharu Morimoto, including Peking duck." },
    { id: "jaleo", name: "Jaleo by José Andrés", where: "Disney Springs", park: "springs",
      kind: "table", price: 3, credits: null, adv: 2, adults: 2,
      note: "Spanish tapas and paella cooked over an open fire." },
    { id: "wine-bar-george", name: "Wine Bar George", where: "Disney Springs", park: "springs", menu: "disney-springs/wine-bar-george",
      kind: "table", price: 3, credits: null, kids: 0, adults: 2, celebrate: ["anniversary"],
      note: "Shareable plates and a huge wine list from a master sommelier." },
    { id: "summer-house", name: "Summer House on the Lake", where: "Disney Springs", park: "springs", menu: "disney-springs/summer-house-on-the-lake",
      kind: "table", price: 3, credits: null, adults: 2,
      note: "California-style dishes in a breezy lakeside setting." },
    { id: "terralina", name: "Terralina Crafted Italian", where: "Disney Springs", park: "springs",
      kind: "table", price: 3, credits: null, picky: 2,
      note: "Italian dishes with a waterfront patio." },
    { id: "frontera", name: "Frontera Cocina", where: "Disney Springs", park: "springs", menu: "disney-springs/frontera-cocina",
      kind: "table", price: 3, credits: null, adults: 2,
      note: "Mexican cooking from Chef Rick Bayless." },
    { id: "city-works", name: "City Works Eatery & Pour House", where: "Disney Springs", park: "springs",
      kind: "table", price: 2, credits: null, picky: 2, adults: 2,
      note: "A sports bar with dozens of TVs and craft beers." },
    { id: "maria-enzo", name: "Maria & Enzo's Ristorante", where: "Disney Springs", park: "springs", menu: "disney-springs/maria-enzo",
      kind: "table", price: 3, credits: null, adults: 2,
      note: "Italian trattoria in a 1930s airline terminal." },
    { id: "enzos-hideaway", name: "Enzo's Hideaway", where: "Disney Springs", park: "springs", menu: "disney-springs/enzos-hideaway",
      kind: "table", price: 3, credits: null, kids: 0, adults: 2,
      note: "A speakeasy-style tunnel bar and Roman-style Italian restaurant." },
    { id: "rainforest-springs", name: "Rainforest Cafe", where: "Disney Springs", park: "springs",
      kind: "table", price: 3, credits: null, themes: ["animals"], picky: 2, adv: 0, kids: 2, adults: 0, celebrate: ["birthday"],
      note: "Animatronic animals, thunderstorms and an erupting volcano." },
    { id: "trex", name: "T-REX Cafe", where: "Disney Springs", park: "springs",
      kind: "table", price: 3, credits: null, themes: ["animals"], picky: 2, adv: 0, kids: 2, adults: 0, celebrate: ["birthday"],
      note: "Life-size animatronic dinosaurs, meteor showers and a fossil dig." },
    { id: "planet-hollywood", name: "Planet Hollywood", where: "Disney Springs", park: "springs",
      kind: "table", price: 3, credits: null, picky: 2, adv: 0, kids: 2,
      note: "Movie memorabilia, burgers and oversized milkshakes." },
    { id: "house-of-blues", name: "House of Blues Restaurant & Bar", where: "Disney Springs", park: "springs",
      kind: "table", price: 3, credits: null, adults: 2,
      note: "Southern food and live music, with a Sunday gospel brunch." },
    { id: "the-edison", name: "The Edison", where: "Disney Springs", park: "springs",
      kind: "table", price: 3, credits: null, adults: 2,
      note: "An industrial-era power plant turned supper club with live entertainment." },
    { id: "polite-pig", name: "The Polite Pig", where: "Disney Springs", park: "springs",
      kind: "quick", price: 2, credits: null, picky: 2, adults: 2,
      note: "Barbecue and bourbon at a counter-service price." },
    { id: "chicken-guy", name: "Chicken Guy!", where: "Disney Springs", park: "springs",
      kind: "quick", price: 1, credits: null, picky: 2, adv: 0, kids: 2,
      note: "Chicken tenders with a wall of dipping sauces." },
    { id: "earl-of-sandwich", name: "Earl of Sandwich", where: "Disney Springs", park: "springs",
      kind: "quick", price: 1, credits: null, picky: 2, adv: 0,
      note: "Hot sandwiches at some of the lowest prices at Disney Springs." },
    { id: "blaze", name: "Blaze Fast-Fire'd Pizza", where: "Disney Springs", park: "springs",
      kind: "quick", price: 1, credits: null, picky: 2, adv: 0, kids: 2,
      note: "Build-your-own pizzas made in minutes." },
    { id: "cookes", name: "Cookes of Dublin", where: "Disney Springs", park: "springs",
      kind: "quick", price: 1, credits: null, picky: 2, adv: 0,
      note: "Fish and chips from Raglan Road's sister counter." },
    { id: "pepe", name: "Pepe by José Andrés", where: "Disney Springs", park: "springs",
      kind: "quick", price: 2, credits: null,
      note: "Spanish sandwiches and small plates at a counter." }
  ]
};
